# Generated by Django 5.0.6 on 2024-07-05 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('baby_id', models.CharField(max_length=100)),
                ('baby_birthdate', models.DateField()),
                ('baby_gender', models.CharField(choices=[('M', '남성'), ('F', '여성'), ('O', '기타')], max_length=1)),
                ('mom_id', models.CharField(max_length=100)),
                ('mom_birthdate', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
